AWSTemplateFormatVersion: '2010-09-09'
Description: Infrastructure to launch load test fleet and all ancillary compnents.

Mappings:
  AccountsMap:
    "306496942465":
      amiid: "ami-08bb13b38534c6abe"
      TPS: 5
    "080387808500":
      amiid: "ami-08bb13b38534c6abe"
      TPS: 5
    "320086063710":
      amiid: "ami-08bb13b38534c6abe"
      TPS: 5
    "302729982612":
      amiid: "ami-08bb13b38534c6abe"
      TPS: 5
    "616166470581":
      amiid: "ami-08bb13b38534c6abe"
      TPS: 5
    "100106417351":
      amiid: "ami-08bb13b38534c6abe"
      TPS: 5


Parameters:
  AmazonEC2FullAccess:
    Type: String
    Description: AmazonEC2FullAccess
    Default: "arn:aws:iam::aws:policy/AmazonEC2FullAccess"
  AmazonSQSFullAccess:
    Type: String
    Description: AmazonSQSFullAccess
    Default: "arn:aws:iam::aws:policy/AmazonSQSFullAccess"
  AmazonS3FullAccess:
    Type: String
    Description: AmazonS3FullAccess
    Default: "arn:aws:iam::aws:policy/AmazonS3FullAccess"
  CloudWatchAgentServerPolicy:
    Type: String
    Description: CloudWatchAgentServerPolicy
    Default: "arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy"
  CloudWatchFullAccess:
    Type: String
    Description: CloudWatchFullAccess
    Default: "arn:aws:iam::aws:policy/CloudWatchFullAccess"
  AmazonChimeFullAccess:
    Type: String
    Description: AmazonChimeFullAccess
    Default: "arn:aws:iam::aws:policy/AmazonChimeFullAccess"
  AmazonSSMManagedInstanceCore:
    Type: String
    Description: AmazonSSMManagedInstanceCore
    Default: "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
  CloudWatchLogsFullAccess:
    Type: String
    Description: CloudWatchLogsFullAccess
    Default: "arn:aws:iam::aws:policy/CloudWatchLogsFullAccess"
  AmazonChimeSDK:
    Type: String
    Description: AmazonChimeSDK
    Default: "arn:aws:iam::aws:policy/AmazonChimeSDK"
  AWSCloudFormationFullAccess:
    Type: String
    Description: AWSCloudFormationFullAccess
    Default: "arn:aws:iam::aws:policy/AWSCloudFormationFullAccess"
Resources:
  LoadTestInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub "LoadTestInstanceProfile-${AWS::AccountId}"
      Roles:
        - !Ref LoadTestIAMRole
  LoadTestIAMRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - !Ref AmazonEC2FullAccess
        - !Ref AmazonSQSFullAccess
        - !Ref AmazonS3FullAccess
        - !Ref CloudWatchAgentServerPolicy
        - !Ref CloudWatchFullAccess
        - !Ref AmazonChimeFullAccess
        - !Ref AmazonSSMManagedInstanceCore
        - !Ref CloudWatchLogsFullAccess
        - !Ref AmazonChimeSDK
        - !Ref AWSCloudFormationFullAccess
  LoadTestLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        InstanceType: c5.9xlarge
        TagSpecifications:
          - ResourceType: "instance"
            Tags:
              - Key: "OdinSon"
                Value: "ThunderLoadTest"
              - Key: "Name"
                Value: "Smoke LoadTest"
        DisableApiTermination: 'false'
        ImageId: !FindInMap
          - AccountsMap
          - !Ref 'AWS::AccountId'
          - amiid
        IamInstanceProfile:
          Arn: !GetAtt LoadTestInstanceProfile.Arn
      LaunchTemplateName: !Sub "LoadTestLaunchTemplate-${AWS::AccountId}"
  LoadTestFleetLaunch:
    Type: AWS::EC2::EC2Fleet
    Properties:
      LaunchTemplateConfigs:
      - LaunchTemplateSpecification:
          LaunchTemplateId:
            Ref: LoadTestLaunchTemplate
          Version: 1
      TargetCapacitySpecification:
        TotalTargetCapacity: !FindInMap
          - AccountsMap
          - !Ref 'AWS::AccountId'
          - TPS
        DefaultTargetCapacityType: "on-demand"
